steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/just-terminus-462608-a8/docker-registry/flask-app:$COMMIT_SHA', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/just-terminus-462608-a8/docker-registry/flask-app:$COMMIT_SHA']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    secretEnv: ['DB_PASSWORD', 'API_KEY']
    args:
      - 'run'
      - 'deploy'
      - 'flask-app-test'
      - '--image'
      - 'us-central1-docker.pkg.dev/just-terminus-462608-a8/docker-registry/flask-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '128Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--port'
      - '5000'
      - '--quiet'
      - '--set-secrets=DB_PASSWORD=DB_PASSWORD:latest,API_KEY=API_KEY:latest'
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'add-iam-policy-binding'
      - 'flask-app-test'
      - '--region'
      - 'us-central1'
      - '--member'
      - 'allUsers'
      - '--role'
      - 'roles/run.invoker'

serviceAccount: 603483693640-compute@developer.gserviceaccount.com

availableSecrets:
  secretManager:
    - versionName: projects/just-terminus-462608-a8/secrets/DB_PASSWORD/versions/latest
      env: 'DB_PASSWORD'
    - versionName: projects/just-terminus-462608-a8/secrets/API_KEY/versions/latest
      env: 'API_KEY'


options:
  logging: CLOUD_LOGGING_ONLY